GET http://localhost:8090/rest/m1.do

###

GET http://localhost:8090/rest/m2.do

###
GET http://localhost:8090/rest/m3.do

###
POST http://localhost:8090/rest/address HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "name": "다다다",
    "age": 28,
    "gender": "f",
    "address": "서울시 강남구 역삼동"
}